apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongdb-pv
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: "/data/mongodb"

  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: mongdb-pvc
    namespace: chatapp
